server:
  port: 8090

spring:
  application:
    name: Loan Service


  #  h2 database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
