# mandatory code
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

account:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@bankapp.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371