server:
  port: 8090

spring:
  application:
    name: Loan Service

#  #  database configuration
#  datasource:
#    url: jdbc:mysql://localhost:3306/loan_microservice
#    username: root
#    password: Amit@1999
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  #  h2 database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
