server:
  port: 8071

spring:
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmitParouha/configserver.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

  application:
    name: "configserver"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "olpsO+CZ/Yy2jaJeU5q39g=="

