server:
  port: 9000

spring:
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"

  application:
    name: Card Service

#  #  database configuration
#  datasource:
#    url: jdbc:mysql://localhost:3306/card_microservice
#    username: root
#    password: Amit@1999
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  #  h2 database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "3.0"

account:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Amit Parouha - Developer"
    email: "amit@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384